name: Flask CI/CD

on:
  push:
    branches:
      - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flask
          pip install boto3
          pip install flask_sqlalchemy
          pip install flask_jwt_extended
          pip install werkzeug

      - name: Verify Python file
        run: |
          python -m py_compile app.py

      - name: Build Docker image
        run: |
          docker build -t flask-localstack .

      - name: Success message
        run: echo "CI/CD Pipeline Success"
